"""indirme merkezi releases

Revision ID: 171595714890
Revises: 61cb2ddf74fa
Create Date: 2026-10-05 11:57:41.421454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '171595714890'
down_revision: Union[str, None] = '61cb2ddf74fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('releases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=30), nullable=False),
    sa.Column('package_type', sa.Enum('DOCKER_LINUX', 'DOCKER_WINDOWS', 'NATIVE_WINDOWS', name='packagetype', native_enum=False, length=20), nullable=False),
    sa.Column('os', sa.String(length=30), nullable=False),
    sa.Column('arch', sa.String(length=30), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('signed', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'version', 'package_type', name='uq_releases_product_version_package_type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('releases')
    # ### end Alembic commands ###
