"""kullanici is_staff alani

Revision ID: a2e20db52f70
Revises: f21ea6e555c2
Create Date: 2026-09-26 19:51:22.747021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2e20db52f70'
down_revision: Union[str, None] = 'f21ea6e555c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # `server_default` elle eklendi (autogenerate koymuyor): var olan
    # `users` satırları için NOT NULL bir kolon eklerken zorunlu — aksi
    # hâlde mevcut satırlarda değer olmadığından ALTER TABLE başarısız
    # olur. Varsayılan `false` — yeni sütun eklenene kadar hiç kimse
    # personel değildi.
    op.add_column('users', sa.Column('is_staff', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_staff')
    # ### end Alembic commands ###
