"""lisans birimi makine adet alani

Revision ID: ab7f5d3b2823
Revises: d2e4da56e351
Create Date: 2026-10-05 14:38:07.170469

KARAR (2026-10-05, kullanıcı): lisans birimi MAKİNE. Var olan siparişler
(varsa) tek makine/koltuk olarak yorumlanır — `server_default='1'`
(KDV migration'ındaki `vat_amount` için kullanılan AYNI güvenlik gerekçesi:
mevcut veri gerçek müşteri siparişi değilse bile NOT NULL'un güvenli bir
varsayılanla gelmesi gerekir).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab7f5d3b2823'
down_revision: Union[str, None] = 'd2e4da56e351'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('quantity', sa.Integer(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'quantity')
    # ### end Alembic commands ###
