"""giris denemesi takibi

Revision ID: d2e4da56e351
Revises: 782028e062d9
Create Date: 2026-10-05 14:11:33.971672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2e4da56e351'
down_revision: Union[str, None] = '782028e062d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_login_attempts_kind_email_created', 'login_attempts', ['kind', 'email', 'created_at'], unique=False)
    op.create_index('ix_login_attempts_kind_ip_created', 'login_attempts', ['kind', 'ip_address', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_login_attempts_kind_ip_created', table_name='login_attempts')
    op.drop_index('ix_login_attempts_kind_email_created', table_name='login_attempts')
    op.drop_table('login_attempts')
    # ### end Alembic commands ###
