/** Arayüzdeki TÜM kullanıcıya görünür metin burada — proje Türkçe-yalnız
 * (ikinci bir dil/çeviri altyapısı bu turun kapsamı dışında, bkz. görev
 * notu "i18n altyapısını basit tut, metinler tek dosyada"). Sayfalar
 * metni doğrudan JSX'e yazmak yerine buradan okur. */
export const strings = {
  nav: {
    urunler: 'Ürünler',
    siparislerim: 'Siparişlerim',
    aboneliklerim: 'Aboneliklerim',
    aktivasyon: 'Çevrimdışı Aktivasyon',
    indirmeler: 'İndirmeler',
    deneme: 'Deneme',
    personel: 'Personel',
    girisYap: 'Giriş Yap',
    kayitOl: 'Kayıt Ol',
    cikisYap: 'Çıkış Yap',
    baslik: 'EGE Lisans Portalı',
  },
  giris: {
    baslik: 'Giriş Yap',
    eposta: 'E-posta',
    parola: 'Parola',
    gonder: 'Giriş Yap',
    gonderiliyor: 'Giriş yapılıyor…',
    hesapYok: 'Hesabınız yok mu?',
    kayitLink: 'Kayıt olun',
  },
  kayit: {
    baslik: 'Kayıt Ol',
    kurumAdi: 'Kurum adı',
    eposta: 'E-posta',
    parola: 'Parola',
    parolaTekrar: 'Parola (tekrar)',
    gonder: 'Kayıt Ol',
    gonderiliyor: 'Kayıt yapılıyor…',
    parolaUyusmuyor: 'Parolalar eşleşmiyor.',
    hesapVar: 'Zaten hesabınız var mı?',
    girisLink: 'Giriş yapın',
  },
  planlar: {
    baslik: 'Ürünler ve Fiyatlar',
    yukleniyor: 'Planlar yükleniyor…',
    bos: 'Şu anda satışta bir plan yok.',
    ay: 'ay',
    netTutar: 'Net tutar',
    kdvOrani: 'KDV oranı',
    kdvDahilToplam: 'KDV dahil toplam',
    siparisVer: 'Sipariş Ver',
    tamSurum: 'Tam sürüm',
    hata: 'Planlar yüklenemedi.',
  },
  siparis: {
    baslik: 'Sipariş Özeti',
    planBulunamadi: 'Sipariş özeti bulunamadı — Ürünler sayfasından tekrar seçin.',
    sure: 'Süre',
    net: 'Net tutar (KDV hariç)',
    kdv: 'KDV',
    toplam: 'Toplam (KDV dahil)',
    onayla: 'Siparişi Onayla',
    onaylaniyor: 'Sipariş oluşturuluyor…',
    alindiBaslik: 'Siparişiniz alındı',
    alindiMesaj: 'Siparişiniz alındı.',
    adet: 'Makine (kurulum) adedi',
    adetAciklama: 'Her makine için ayrı bir lisans etkinleştirilir. Fiyatlar 1 makine içindir; kesin tutar sipariş onaylanınca sunucudan gelir.',
    birimFiyat: '1 makine için',
    adetGecersiz: 'Makine adedi 1 ile 100 arasında bir tam sayı olmalı.',
    odeme: 'Ödeme',
    odemeBaslik: 'Ödeme altyapısı yakında',
    odemeBilgi:
      'Çevrimiçi ödeme henüz devrede değil. Ödeme talimatı için sipariş numaranızla team@bigventus.com adresine yazın; ödemeniz onaylanınca aboneliğiniz otomatik açılır ve Aboneliklerim sayfasında görünür.',
    siparisNo: 'Sipariş No',
    aboneliklereDon: 'Aboneliklerime git',
  },
  abonelikler: {
    baslik: 'Aboneliklerim',
    yukleniyor: 'Abonelikler yükleniyor…',
    bos: 'Henüz bir aboneliğiniz yok.',
    durum: 'Durum',
    bitisTarihi: 'Bitiş tarihi',
    urunler: 'Ürünler',
    lisanslar: 'Verilen lisanslar',
    lisansYok: 'Bu abonelik için henüz verilmiş bir lisans yok.',
    verilis: 'Veriliş',
    bitis: 'Bitiş',
    yenidenIndir: 'Yeniden İndir',
    indiriliyor: 'İndiriliyor…',
    durumAktif: 'aktif',
    durumSuresiDolmus: 'süresi dolmuş',
    durumIptal: 'iptal edildi',
  },
  aktivasyon: {
    baslik: 'Çevrimdışı Aktivasyon',
    aciklama:
      'Her ürünün kendi "Lisans" ekranından indirdiğiniz activation_request.json dosyalarını buraya yükleyin. Abonelikteki HER ürün için tam olarak bir dosya gerekir.',
    abonelikSec: 'Abonelik seçin',
    beklenenUrunler: 'Bu abonelikte beklenen ürünler',
    dosyaSec: 'activation_request.json dosyaları seçin',
    gonder: 'Lisans Üret',
    gonderiliyor: 'Lisans üretiliyor…',
    basarili: 'license.json indirildi.',
    dosyaCokBuyuk: (ad: string) => `"${ad}" çok büyük (en çok 16 KB olmalı).`,
    abonelikYok: 'Önce bir abonelik satın almalısınız.',
  },
  indirmeler: {
    baslik: 'İndirmeler',
    yukleniyor: 'Sürümler yükleniyor…',
    bos: 'İndirebileceğiniz bir sürüm yok.',
    surum: 'Sürüm',
    paketTuru: 'Paket türü',
    platform: 'Platform',
    boyut: 'Boyut',
    sha256: 'SHA-256',
    kopyala: 'Kopyala',
    kopyalandi: 'Kopyalandı',
    indir: 'İndir',
    indiriliyor: 'İndiriliyor…',
    imzasiz: 'İMZASIZ (yalnız personel)',
  },
  deneme: {
    baslik: 'Deneme Lisansı',
    aciklama:
      'Denemek istediğiniz her ürünün "Lisans" ekranından indirdiğiniz activation_request.json dosyasını yükleyin.',
    sure: (gun: number) => `Size tanımlı deneme süresi: ${gun} gün.`,
    dosyaSec: 'activation_request.json dosyaları seçin',
    gonder: 'Deneme Lisansı Üret',
    gonderiliyor: 'Deneme lisansı üretiliyor…',
    basarili: 'Deneme license.json indirildi.',
    dosyaCokBuyuk: (ad: string) => `"${ad}" çok büyük (en çok 16 KB olmalı).`,
  },
  siparisler: {
    baslik: 'Siparişlerim',
    yukleniyor: 'Siparişler yükleniyor…',
    bos: 'Henüz bir siparişiniz yok.',
    siparisNo: 'Sipariş No',
    tarih: 'Tarih',
    sure: 'Süre',
    ay: 'ay',
    adet: 'Makine adedi',
    net: 'Net',
    kdv: 'KDV',
    toplam: 'Toplam',
    durum: 'Durum',
    durumlar: {
      pending: 'Ödeme bekleniyor',
      paid: 'Ödendi',
      failed: 'Ödeme başarısız',
      cancelled: 'İptal edildi',
    } as Record<string, string>,
    bekleyenBilgi:
      'Ödeme bekleyen siparişler için ödeme talimatını sipariş numaranızla team@bigventus.com adresinden isteyebilirsiniz.',
  },
  genel: {
    oturumKontrol: 'Oturum kontrol ediliyor…',
    cikisYapiliyor: 'Çıkış yapılıyor…',
    kapat: 'Kapat',
  },
  personel: {
    baslik: 'Bekleyen Siparişler',
    yukleniyor: 'Siparişler yükleniyor…',
    bos: 'Bekleyen sipariş yok.',
    musteri: 'Müşteri',
    plan: 'Plan',
    sure: 'Süre',
    toplam: 'Toplam',
    olusturulma: 'Oluşturulma',
    odendiIsaretle: 'Ödendi İşaretle',
    formBaslik: 'Ödeme Bilgisi',
    tutarSalt: 'Tutar (sipariş toplamı — değiştirilemez)',
    dogrulamaOnayi: 'Banka hesabına bu tutarın geldiğini doğruladım.',
    referans: 'Banka referansı (dekont/işlem no)',
    tarih: 'Ödemenin bankaya geçtiği tarih',
    not: 'Not (opsiyonel)',
    gonder: 'Kaydet',
    gonderiliyor: 'Kaydediliyor…',
    basarili: 'Ödeme işaretlendi, abonelik açıldı.',
    vazgec: 'Vazgeç',
  },
} as const
